name: Sparrow SAST Analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Sparrow CLI
        run: |
          curl -L -o https://localhost:18080
          tar -xzvf sparrow-cli.tar.gz
          chmod +x sparrow-client.sh
          export PATH=$PATH:$PWD

      - name: Analyze All Folders
        run: |
          for folder in $(find ./Juliet-Code-C -type d -mindepth 1 -maxdepth 1); do
            ./sparrow-client.sh -S https://localhost:18080 -U admin -PW 1234qwer!@#$ -P Juliet-Code-C -SD "$folder" -F
          done

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: sparrow-report
          path: ./output
